[package]
name = "vault_allocator"
version.workspace = true
edition.workspace = true
cairo-version.workspace = true
scarb-version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
repository.workspace = true
license-file.workspace = true

[tool]
fmt.workspace = true

[[tool.snforge.fork]]
name = "MAINNET"
url = "https://rpc.starknet.lava.build"
block_id.number = "4343594"

[[tool.snforge.fork]]
name = "LZ"
url = "https://rpc.starknet.lava.build"
block_id.number = "4343594"


[[tool.snforge.fork]]
name = "STARKGATE_MIDDLEWARE"
url = "https://rpc.starknet.lava.build"
block_id.number = "4336541"

[[tool.snforge.fork]]
name = "CCTP_MIDDLEWARE"
url = "https://rpc.starknet.lava.build"
block_id.number = "4336541"

[[tool.snforge.fork]]
name = "HYPERLANE_MIDDLEWARE"
url = "https://rpc.starknet.lava.build"
block_id.number = "4336541"

[[tool.snforge.fork]]
name = "BASE_MIDDLEWARE"
url = "https://rpc.starknet.lava.build"
block_id.number = "4336541"

[[tool.snforge.fork]]
name = "LZ_MIDDLEWARE"
url = "https://rpc.starknet.lava.build"
block_id.number = "4336541"


[[tool.snforge.fork]]
name = "AVNU"
url = "https://rpc.starknet.lava.build"
block_id.number = "1781028"


[[tool.snforge.fork]]
name = "EKUBO"
url = "https://rpc.starknet.lava.build"
block_id.number = "4077824"

[[tool.snforge.fork]]
name = "SSCL"
url = "https://rpc.starknet.lava.build"
block_id.number = "1784627"

[[tool.snforge.fork]]
name = "SLLSE"
url = "https://rpc.starknet.lava.build"
block_id.number = "1794270"

[dependencies]
starknet.workspace = true
openzeppelin.workspace = true
alexandria_math.workspace = true
alexandria_bytes.workspace = true
ekubo.workspace = true


[dev-dependencies]
snforge_std.workspace = true

[lib]

[[target.starknet-contract]]
allowed-libfuncs-list.name = "experimental"
sierra = true
casm = true
casm-add-pythonic-hints = true